from __future__ import annotations

from typing import List, Optional

from sqlalchemy import delete, select
from sqlalchemy.orm import Session, selectinload

from app.models import CanonicalDocument, ProvenanceAnchor
from app.schemas import CanonicalDocumentUpsert, ProvenanceAnchorCreate


class CanonicalDocumentRepository:
    """Persist canonical text documents and provenance anchors."""

    def __init__(self, session: Session):
        self.session = session

    def get_document(
        self,
        notice_id: int,
        attachment_id: Optional[int],
        document_kind: str,
    ) -> Optional[CanonicalDocument]:
        """Fetch the canonical document for a notice/attachment scope."""

        statement = (
            select(CanonicalDocument)
            .where(CanonicalDocument.notice_id == notice_id)
            .where(CanonicalDocument.attachment_id == attachment_id)
            .where(CanonicalDocument.document_kind == document_kind)
            .options(selectinload(CanonicalDocument.provenance_anchors))
        )
        return self.session.scalar(statement)

    def list_documents_for_notice(self, notice_id: int) -> List[CanonicalDocument]:
        """List all canonical documents for one notice in stable processing order."""

        statement = (
            select(CanonicalDocument)
            .where(CanonicalDocument.notice_id == notice_id)
            .order_by(CanonicalDocument.attachment_id.is_not(None), CanonicalDocument.id.asc())
        )
        return list(self.session.scalars(statement))

    def upsert_document(self, payload: CanonicalDocumentUpsert) -> CanonicalDocument:
        """Insert or refresh a canonical document generated by normalization."""

        document = self.get_document(
            notice_id=payload.notice_id,
            attachment_id=payload.attachment_id,
            document_kind=payload.document_kind,
        )
        payload_data = payload.model_dump()
        payload_data["blocks_json"] = [block.model_dump() for block in payload.blocks]
        payload_data["metadata_json"] = payload_data.pop("metadata")
        payload_data.pop("blocks")

        if document is None:
            document = CanonicalDocument(**payload_data)
            self.session.add(document)
        else:
            for field_name, value in payload_data.items():
                setattr(document, field_name, value)

        self.session.flush()
        return document

    def replace_anchors(
        self,
        document_id: int,
        anchors: List[ProvenanceAnchorCreate],
    ) -> List[ProvenanceAnchor]:
        """Replace the full set of provenance anchors for one document."""

        self.session.execute(
            delete(ProvenanceAnchor).where(ProvenanceAnchor.document_id == document_id)
        )

        saved_anchors = []
        for payload in anchors:
            payload_data = payload.model_dump()
            payload_data["locator_json"] = payload_data.pop("locator")
            anchor = ProvenanceAnchor(**payload_data)
            self.session.add(anchor)
            saved_anchors.append(anchor)

        self.session.flush()
        return saved_anchors

    def list_anchors(self, document_id: int) -> List[ProvenanceAnchor]:
        """List anchors in stable order for explanation or testing flows."""

        statement = (
            select(ProvenanceAnchor)
            .where(ProvenanceAnchor.document_id == document_id)
            .order_by(ProvenanceAnchor.id.asc())
        )
        return list(self.session.scalars(statement))
